apiVersion: apps/v1
kind: Deployment
metadata:
  name: robson-deployment
spec:
  selector:
    matchLabels:
      app: site
  replicas: 2
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
      - name: site
        image: ivanzy/k8s-robson
        ports:
        - containerPort: 80